//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 10:50:29 PM GMT 
//


package net.mikecarr.ws.employees_web_service;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dept.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dept">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FINANCE"/>
 *     &lt;enumeration value="IT"/>
 *     &lt;enumeration value="ENGINEERING"/>
 *     &lt;enumeration value="USD"/>
 *     &lt;enumeration value="HR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dept")
@XmlEnum
public enum Dept {

    FINANCE,
    IT,
    ENGINEERING,
    USD,
    HR;

    public String value() {
        return name();
    }

    public static Dept fromValue(String v) {
        return valueOf(v);
    }

}
