//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.18 at 10:50:29 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mikecarr.net/ws/employees-web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.mikecarr.ws.employees_web_service;
